marks = []
student = int(input("Enter your marks :- "))
marks.append(student)
student = int(input("Enter your marks :- "))
marks.append(student)
student = int(input("Enter your marks :- "))
marks.append(student)
student = int(input("Enter your marks :- "))
marks.append(student)
student = int(input("Enter your marks :- "))
marks.append(student)
student = int(input("Enter your marks :- "))
marks.append(student)
marks.sort()
print(marks)