fruits = []
fruits_1 = input("Enter the fruits name :- ")
fruits.append(fruits_1)
fruits_1 = input("Enter the fruits name :- ")
fruits.append(fruits_1)
fruits_1 = input("Enter the fruits name :- ")
fruits.append(fruits_1)
fruits_1 = input("Enter the fruits name :- ")
fruits.append(fruits_1)
fruits_1 = input("Enter the fruits name :- ")
fruits.append(fruits_1)
fruits_1 = input("Enter the fruits name :- ")
fruits.append(fruits_1)
fruits_1 = input("Enter the fruits name :- ")
fruits.append(fruits_1)
print(fruits)